language: c

os: osx

osx_image: xcode9.4

compiler: clang

sudo: false

env:
  - VIMCMD=/usr/local/opt/macvim/MacVim.app/Contents/MacOS/Vim

addons:
  homebrew:
    packages:
      - ruby
    update: true

script:
  - brew audit --strict --except=specs macvim.rb
  - brew install --HEAD ./macvim.rb
  - |
    macvim_excmd() {
      ${VIMCMD} -u NONE -i NONE -g -f -X -V1 -es "$@" -c 'echo ""' -c quit 2>&1
    }
  - macvim_excmd -c 'lua print("Test")' | grep -qw Test
  - macvim_excmd -c 'perl VIM::Msg("Test")' | grep -qw Test
  - macvim_excmd -c 'py import sys; print("Test")' | grep -qw Test
  - macvim_excmd -c 'py3 import sys; print("Test")' | grep -qw Test
  - macvim_excmd -c 'ruby puts("Test")' | grep -qw Test

# vim:set sts=2 sw=2 tw=0 et:
